### PR TITLE
history section added

### PR DESCRIPTION
**Pull request by PeterTurcan**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Maybe @sdarwin can check to see if there are any other non-html documents on the server?

**Comment by sdarwin** [comment]
The boostorg website is stored in the repository https://github.com/boostorg/website

It has the these PDF files:
website/community/blom_libraries/BLOM_MoU_v0.pdf
website/users/proposal.pdf

Also rst files:
development/report-apr-2006.rst
development/report-apr-2008.rst
development/report-dec-2009.rst
development/report-jan-2006.rst
development/report-jun-2009.rst
development/report-may-2008.rst
development/report-nov-2007.rst
development/report-nov-2008.rst
development/report-sep-2007.rst

And many PHP files.

**Comment by vinniefalco** [comment]
yeah I dpnt care too much about the php but the rst is interesting

**Comment by PeterTurcan** [comment]
@sdarwin Good info - I have added links to the rst files to my history topic. I cannot find a **blom_libraries** folder under the communities folder - any insight - do I need to update something?

**Comment by sdarwin** [comment]
Looks like Glen removed that directory in Feb 2023 https://github.com/boostorg/website/commit/7bee278d220d1c6e954ba4648146936b31d27e3c

**Pull request merged**
