### PR TITLE
Moved Style Guide into Contributor Guide

### PR DESCRIPTION
**Pull request by PeterTurcan**
Moved the Boost Style Guide into the Community section, and renamed Site-docs Style Guide, as we already have an Asciidoc Style Guide. Minor heading corrections to Tweeting.

### CODE REVIEW

**Comment by alandefreitas** [comment]
CI failed: https://github.com/cppalliance/site-docs/actions/runs/6843221853/job/18605573428?pr=151#step:4:123

Is it from this PR?

**Review by alandefreitas — APPROVED** [review]

**Comment by PeterTurcan** [comment]
@alandefreitas  Hmm, I did not touch the User Guide, so not sure where this error came from:  

 Start page specified for site not found: user-guide::index.adoc

**Comment by alandefreitas** [comment]
Some commit must have removed this index.adoc file. I suspect that's why we didn't get a preview.

**Comment by PeterTurcan** [comment]
@alandefreitas OK - added index.adoc back in with this commit, to test out?

**Comment by alandefreitas** [comment]
Same error:

user-guide::index.adoc

Also, 13b3997180a1074817425b65f39db2ac2cefa68d did not readd index.adoc. It just changed a line on a file that already existed.

It might be an error with the component name or something like that. I don't know yet.

**Comment by PeterTurcan** [comment]
@alandefreitas OK, I don't really have any insight into what might cause this error, though let me know if there is something I should try.

**Comment by alandefreitas** [comment]
> @alandefreitas OK, I don't really have any insight into what might cause this error, though let me know if there is something I should try.

I don't really know what's causing the error. It's probably just a matter of some trial and error, but I'm not able to do that right now because there's some other ultra-urgent stuff going on.

**Comment by PeterTurcan** [comment]
Good to hear, thanks.

**Pull request closed without merging**
