### PR TITLE
Updated Headers, Separate Compilation topics

### PR DESCRIPTION
**Pull request by PeterTurcan**
Read and edited Headers and Separate Compilation legacy sections

### CODE REVIEW

**Comment by alandefreitas** [comment]
Looks good.

I've never seen the `BOOST\_FURBALL\_HPP` though. I didn't even know `\_` was valid C++.

It's worth going through the libraries to make sure that's the case, but I think all libraries I've seen so far follow a convention like `BOOST_<LIBRARY>_<PATH>_HPP`. For instance:

https://github.com/boostorg/url/blob/develop/include/boost/url/detail/any_params_iter.hpp

**Comment by PeterTurcan** [comment]
Agreed on the header guards, clarified and added an example.

**Comment by alandefreitas** [comment]
Great. Please squash when ready. :+1:

**Comment by PeterTurcan** [comment]
@alandefreitas - squashed

**Pull request merged**
