### PR TITLE
Replace all \_ with _ in Contributor Guide

### PR DESCRIPTION
**Pull request by PeterTurcan**
Simple PR to remove all the unnecessary escape characters.

### CODE REVIEW

**Comment by alandefreitas** [comment]
This seems to replicate the "[Boost Test Matrix section updated](https://github.com/cppalliance/site-docs/pull/134/commits/a67858e8f1888217a65eb22ea12dc79e3ef43c0a)" commit from your last PR you just closed because it "requires further research".

**Comment by PeterTurcan** [comment]
@alandefreitas Oops, missed a step, intended to replace the test matrix with a stub.

**Comment by alandefreitas** [comment]
In a PR, you should usually just remove the previous commit instead of including new commit that undoes the previous one. In any case, the whole thing will fix itself by squashing.

**Comment by PeterTurcan** [comment]
@alandefreitas squashed

**Pull request merged**
