### PR TITLE
all evergreen links, URLs work

### PR DESCRIPTION
**Pull request by PeterTurcan**

### CODE REVIEW

**Review by alandefreitas — APPROVED** [review]
Looks good to me

**Comment by PeterTurcan** [comment]
@alandefreitas - thanks for reviewing - can we merge it?

**Comment by alandefreitas** [comment]
>  thanks for reviewing - can we merge it?

Sure. Can I assume you consider the PR good to go as long as it's not a draft?

**Comment by PeterTurcan** [comment]
@alandefreitas - Normally I think it will be good to go, unless you have found issues I should address

**Pull request merged**
